### ISSUE TITLE
ERROR [proxy_rs::resolver] error trying to connect: An existing connection was forcibly closed by the remote host. (os error 10054)

### ISSUE THREAD

**Issue by ramaraf221** [zevtyardt/proxy.rs#4]
![image](https://github.com/zevtyardt/proxy.rs/assets/60566081/8e2c3b9f-dd96-493b-a26e-3359ce058075)

**Comment by lucasbuilds** [comment]
I've never had the same problem before but try to upgrade the driver like [this tutorial](https://www.drivereasy.com/knowledge/an-existing-connections-was-forcibly-closed-by-the-remote-host/#:~:text=So%20if%20you%20receive%20the,your%20drivers%3A%20manually%20and%20automatically.).
