### ISSUE TITLE
ERROR thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: O blablabla

### ISSUE THREAD

**Issue by ikhsanh** [zevtyardt/proxy.rs#5]
$ proxy-rs find --types HTTP HTTPS -l 10 --levels High --countries ID
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 17, kind: CrossesDevices, message: "The system cannot move the file to a different disk drive." }', C:\Users\Ikhsani Hidayat\.cargo\registry\src\index.crates.io-6f17d22bba15001f\proxy-rs-0.2.72\src\utils\geolite_database.rs:130:44
stack backtrace:
   0:     0x7ff77bd981cc - <unknown>
   1:     0x7ff77bdb5feb - <unknown>
   2:     0x7ff77bd93949 - <unknown>
   3:     0x7ff77bd97f7b - <unknown>
   4:     0x7ff77bd9a789 - <unknown>
   5:     0x7ff77bd9a43f - <unknown>
   6:     0x7ff77bd9ac8e - <unknown>
   7:     0x7ff77bd9ab7d - <unknown>
   8:     0x7ff77bd98b49 - <unknown>
   9:     0x7ff77bd9a880 - <unknown>
  10:     0x7ff77be4aab5 - <unknown>
  11:     0x7ff77be4afc3 - <unknown>
  12:     0x7ff77bb0b520 - <unknown>
  13:     0x7ff77bb2230e - <unknown>
  14:     0x7ff77ba23c31 - <unknown>
  15:     0x7ff77ba31a3a - <unknown>
  16:     0x7ff77baff2bf - <unknown>
  17:     0x7ff77b8d7a44 - <unknown>
  18:     0x7ff77bc3926d - <unknown>
  19:     0x7ff77bc360e3 - <unknown>
  20:     0x7ff77bc60d76 - <unknown>
  21:     0x7ff77bc39007 - <unknown>
  22:     0x7ff77bc2fe84 - <unknown>
  23:     0x7ff77bc4e4d0 - <unknown>
  24:     0x7ff77bc4199b - <unknown>
  25:     0x7ff77bc33c9e - <unknown>
  26:     0x7ff77bc4a418 - <unknown>
  27:     0x7ff77bd9fefc - <unknown>
  28:     0x7ffd50f626ad - BaseThreadInitThunk
  29:     0x7ffd5118aa68 - RtlUserThreadStart
ERROR [proxy_rs::judge] <Judge [HTTP] httpbin.org>: Timeout error
ERROR [proxy_rs::judge] <Judge [HTTPS] httpbin.org>: Timeout error

I have been tried to run export RUST_BACKTRACE=1 and export RUST_BACKTRACE=full
but still getting error. how to solve this problem?
I'm using windows 11

**Comment by lucasbuilds** [comment]
Try reinstalling using git

```
cargo install --git https://github.com/zevtyardt/proxy.rs
```

Let me know if this patch works

**Comment by ikhsanh** [comment]
> Try reinstalling using git
> 
> ```
> cargo install --git https://github.com/zevtyardt/proxy.rs
> ```
> 
> Let me know if this patch works

THANKS. IT WORKS 
![WhatsApp Image 2023-08-10 at 09 29 15](https://github.com/zevtyardt/proxy.rs/assets/39503448/e0af6bc8-969f-406e-a706-facaa51b5aee)
