### ISSUE TITLE
No judges found!

### ISSUE THREAD

**Issue by ShayBox** [zevtyardt/proxy.rs#6]
```
WARN  [proxy_rs::checker] Not found judges for the ["HTTP", "HTTPS"] schemes. Checking proxy on protocols ["CONNECT:25", "HTTPS", "HTTP", "SOCKS5", "CONNECT:80", "SOCKS4"] is disabled.
ERROR [proxy_rs::checker] No judges found!
```

I tried `cargo install proxy-rs` and `cargo install --git https://github.com/zevtyardt/proxy.rs.git`

**Comment by lucasbuilds** [comment]
Can you try it again with the `--log debug` flag

**Comment by ShayBox** [comment]
~~This is as much as I can give you, the log is too long to get anything above this~~
https://pastebin.com/yJTMVFzV

EDIT: I found a scroll-back setting
[debug.txt](https://github.com/zevtyardt/proxy.rs/files/13072185/debug.txt)

**Comment by lucasbuilds** [comment]
I have added a new version, you can try it

**Comment by ShayBox** [comment]
It works now, thanks!
