### ISSUE TITLE
ERROR [proxy_rs::judge] <Judge [HTTPS] www.proxyjudge.info>: Error: error trying to connect: tcp connect error: (os error 10061)

### ISSUE THREAD

**Issue by seongs1024** [zevtyardt/proxy.rs#8]
The error occured but when I executed the command once at first time, it gave me the list of proxies though, I don't know why suddenly the proxy-rs not works from second time. It seems like to be hanging

```
> proxy-rs find --types HTTP HTTPS -l 10 --levels High --countries ID
ERROR [proxy_rs::judge] <Judge [HTTPS] www.proxyjudge.info>: Error: error trying to connect: tcp connect error: (os error 10061)

```

**Comment by seongs1024** [comment]
Oh I found that it isn't hanging, after waiting about 5 mins not to kill the process, it was giving the list!
```
proxy-rs find --types HTTP HTTPS -l 10 --levels High --countries ID
ERROR [proxy_rs::judge] <Judge [HTTPS] www.proxyjudge.info>: Error: error trying to connect: tcp connect error: (os error 10061)
<Proxy ID 0.66s [HTTPS, HTTP: High] 147.139.164.26:8118>
```

**Comment by lucasbuilds** [comment]
the logic in searching and checking proxies is not very efficient in the current version. Therefore I plan to rewrite all the code while looking for the most efficient logic/algorithm in searching and checking proxies simultaneously.

**Comment by lucasbuilds** [comment]
And also the log messages are still a little confusing

**Comment by zevtyardt** [comment]
And also the log messages are still a little confusing
